travis:
  secure:
    BINSTAR_TOKEN: bJ2Y3PyJzHYVUXwiVOVs6rd/biRa/b+s9od9LC7JyakR3A1tcNPu+f35nN1PJ5AjkudZvpH06218BFevyY54IwIlfjLIDekL/I6Qyipj8VrrLa8qF77L+6EkBiEMnFXeNOVd3j4fjgI1n5w6/T3rVq2HRzWDGJFF/g6J/i5PJvcDxDQ9GHr6Ok3aKLcEvzvcWV1hTMfuCSVWF2ulXaoMHLL4RNr4kClUinLePzHdkXtYbc9+FNnOUbFHnZQP2chHiK7D/70tqdF7oPYQNEYFv13bPxuAydhj/CqKbeTAwDIS5klBiVIx//KH+Z0wOvl0Q3yIG+r0iYYLN4CeXlTGiqzzjIBptOuQA3uhdQsO/C/pPwuIACD0nfE3gcrPabYZB8W3O6Zv7Hi22WwmBmEYQ1UE+Or2MbTZHGMFeo9fZDekdE6h64aaVdLVixMGazjG/PkIXu+E13TAy5u0KQVPeH9Q53eVeXYOjTbNZRfpvLWdmrNnLfhK64RxXj1V7sHvpsUD1zo/e/GjY6lzvewBCEZ645HE/Grfi7Uixb1tR5RAXOJ2EQfCpUs4AnqAmvB57qp0M0I84cclPewIWNSKFd7/ozv6OSllPgBe78ZEVeTiTQ/9vK0sFD3pMeejAN/JjB84SZf83gobFuLa7RIJ1Is1qx5XWAMmQhM3poPgNuc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
