travis:
  secure:
    BINSTAR_TOKEN: g3QF9e52TlWP10kbhA56bAZCKBAuReb+3OI9NdlB6l2Ol7+wyK/dZvUY3UxnYbhVXkE2TWBHDnA3n1EX8luyLXAJK1PyBy6b6OcgeeB8Jqehq3meIyAVSANl0wnZpgnPQwmC2b4pp9F22KzbF2jE0EgKUtZspFTyLQEKQs+Q6umN0MpQUQB3ktjepD4XLCIRboLi2mW05eIF5mK+dY6s8gjhKpEOgurcsahsTPLPEWJv3DblITIr1+EvUFHSWXNEQepYczDr3a60EaQK4MrPH36pN8AhI2V7Feg1qllipjkaoDD923lez5z/woaoR7ESyifFAMp7+hEkHaQ+MgGXPKrNgCEXV0emABk9O+7EP+5/Je8yn5ycnMW5O8wwCwZVfzgr4I1LfAxm5hcI5XV6mzNEcVDVuVVSdeQ/HAtZFK5WqAoxv1TtfQBLlwoiuUQs9v+LSub6gDfX+yMlh9vDlnzhTcwYNWL5/rmUf3UMgoCj59FwAT9f1iTsq4xC+3LFFMXXaar3l5ZH8F+ziDUT4n3Gwv3wSoDl2EpobJY/I5zm9ht6F5JA+nqenxng8mRI3sp8P4fQrtD/qS3EqIcQgH2V4AxK2RaSDRUaJwz06Jj4S7lI1XI+2bLvkFEdTzs352Gf0m8kpaiW11nPgrTLR77avgGOiytXPZimWwnmalE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
